import { InstrucaoTecnica, CategoriaIT } from '@/types';

export const categoriasIT: CategoriaIT[] = [
  {
    id: 'edificacoes',
    nome: 'Edificações',
    descricao: 'Normas para construções e edificações',
    icone: '🏢',
    count: 15
  },
  {
    id: 'instalacoes',
    nome: 'Instalações',
    descricao: 'Sistemas prediais e instalações',
    icone: '⚡',
    count: 12
  },
  {
    id: 'prevencao',
    nome: 'Prevenção',
    descricao: 'Medidas preventivas de segurança',
    icone: '🛡️',
    count: 18
  },
  {
    id: 'combate',
    nome: 'Combate a Incêndio',
    descricao: 'Sistemas de combate e supressão',
    icone: '🚒',
    count: 20
  },
  {
    id: 'emergencia',
    nome: 'Emergência',
    descricao: 'Procedimentos de emergência',
    icone: '🚨',
    count: 8
  },
  {
    id: 'industria',
    nome: 'Industrial',
    descricao: 'Normas específicas para indústrias',
    icone: '🏭',
    count: 10
  }
];

export const instrucoesPopulares: InstrucaoTecnica[] = [
  {
    id: 'it-001',
    numero: 'IT-001/2023',
    titulo: 'Procedimentos Administrativos',
    descricao: 'Estabelece os procedimentos administrativos para análise de projetos de segurança contra incêndio e pânico.',
    categoria: 'prevencao',
    conteudo: 'Conteúdo completo da IT-001 sobre procedimentos administrativos...',
    versao: '1.0',
    dataPublicacao: '2023-01-15',
    ultimaRevisao: '2023-06-20',
    arquivo: '/docs/it-001-2023.pdf',
    tags: ['procedimentos', 'análise', 'projetos'],
    palavrasChave: ['procedimentos', 'administrativos', 'análise', 'projetos'],
    popular: true,
    visualizacoes: 1250,
    downloads: 340,
    isActive: true,
    metadata: {},
    organizationId: 'cbm-pi',
    slug: 'procedimentos-administrativos',
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2023-06-20T00:00:00Z'
  },
  {
    id: 'it-005',
    numero: 'IT-005/2023',
    titulo: 'Segurança Estrutural contra Incêndio',
    descricao: 'Define os critérios de segurança estrutural contra incêndio para edificações.',
    categoria: 'edificacoes',
    conteudo: 'Conteúdo completo da IT-005 sobre segurança estrutural...',
    versao: '1.0',
    dataPublicacao: '2023-02-10',
    ultimaRevisao: '2023-08-15',
    arquivo: '/docs/it-005-2023.pdf',
    tags: ['estrutural', 'edificações', 'resistência'],
    palavrasChave: ['segurança', 'estrutural', 'incêndio', 'edificações'],
    popular: true,
    visualizacoes: 980,
    downloads: 280,
    isActive: true,
    metadata: {},
    organizationId: 'cbm-pi',
    slug: 'seguranca-estrutural-contra-incendio',
    createdAt: '2023-02-10T00:00:00Z',
    updatedAt: '2023-08-15T00:00:00Z'
  },
  {
    id: 'it-008',
    numero: 'IT-008/2023',
    titulo: 'Saídas de Emergência',
    descricao: 'Estabelece os requisitos para dimensionamento e características das saídas de emergência.',
    categoria: 'emergencia',
    conteudo: 'Conteúdo completo da IT-008 sobre saídas de emergência...',
    versao: '1.0',
    dataPublicacao: '2023-03-05',
    ultimaRevisao: '2023-09-10',
    arquivo: '/docs/it-008-2023.pdf',
    tags: ['saídas', 'emergência', 'dimensionamento'],
    palavrasChave: ['saídas', 'emergência', 'dimensionamento', 'evacuação'],
    popular: true,
    visualizacoes: 1450,
    downloads: 420,
    isActive: true,
    metadata: {},
    organizationId: 'cbm-pi',
    slug: 'saidas-de-emergencia',
    createdAt: '2023-03-05T00:00:00Z',
    updatedAt: '2023-09-10T00:00:00Z'
  },
  {
    id: 'it-012',
    numero: 'IT-012/2023',
    titulo: 'Brigada de Incêndio',
    descricao: 'Define os requisitos para formação e treinamento de brigadas de incêndio.',
    categoria: 'prevencao',
    conteudo: 'Conteúdo completo da IT-012 sobre brigada de incêndio...',
    versao: '1.0',
    dataPublicacao: '2023-04-20',
    ultimaRevisao: '2023-10-05',
    arquivo: '/docs/it-012-2023.pdf',
    tags: ['brigada', 'treinamento', 'prevenção'],
    palavrasChave: ['brigada', 'incêndio', 'treinamento', 'prevenção'],
    popular: true,
    visualizacoes: 890,
    downloads: 210,
    isActive: true,
    metadata: {},
    organizationId: 'cbm-pi',
    slug: 'brigada-de-incendio',
    createdAt: '2023-04-20T00:00:00Z',
    updatedAt: '2023-10-05T00:00:00Z'
  }
];

export const todasInstrucoes: InstrucaoTecnica[] = [
  ...instrucoesPopulares,
  {
    id: 'it-002',
    numero: 'IT-002/2023',
    titulo: 'Terminologia de Segurança contra Incêndio',
    descricao: 'Define os termos técnicos utilizados nas normas de segurança contra incêndio.',
    categoria: 'prevencao',
    conteudo: 'Conteúdo completo da IT-002 sobre terminologia...',
    versao: '1.0',
    dataPublicacao: '2023-01-20',
    ultimaRevisao: '2023-07-15',
    arquivo: '/docs/it-002-2023.pdf',
    tags: ['terminologia', 'definições', 'normas'],
    palavrasChave: ['terminologia', 'segurança', 'incêndio', 'definições'],
    popular: false,
    visualizacoes: 520,
    downloads: 180,
    isActive: true,
    metadata: {},
    organizationId: 'cbm-pi',
    slug: 'terminologia-seguranca-contra-incendio',
    createdAt: '2023-01-20T00:00:00Z',
    updatedAt: '2023-07-15T00:00:00Z'
  },
  {
    id: 'it-003',
    numero: 'IT-003/2023',
    titulo: 'Símbolos Gráficos para Projetos',
    descricao: 'Estabelece os símbolos gráficos a serem utilizados em projetos de segurança.',
    categoria: 'prevencao',
    conteudo: 'Conteúdo completo da IT-003 sobre símbolos gráficos...',
    versao: '1.0',
    dataPublicacao: '2023-01-25',
    ultimaRevisao: '2023-07-20',
    arquivo: '/docs/it-003-2023.pdf',
    tags: ['símbolos', 'gráficos', 'projetos'],
    palavrasChave: ['símbolos', 'gráficos', 'projetos', 'segurança'],
    popular: false,
    visualizacoes: 720,
    downloads: 150,
    isActive: true,
    metadata: {},
    organizationId: 'cbm-pi',
    slug: 'simbolos-graficos-para-projetos',
    createdAt: '2023-01-25T00:00:00Z',
    updatedAt: '2023-07-20T00:00:00Z'
  },
  {
    id: 'it-004',
    numero: 'IT-004/2023',
    titulo: 'Classificação das Edificações',
    descricao: 'Define a classificação das edificações quanto ao risco de incêndio.',
    categoria: 'edificacoes',
    conteudo: 'Conteúdo completo da IT-004 sobre classificação de edificações...',
    versao: '1.0',
    dataPublicacao: '2023-02-01',
    ultimaRevisao: '2023-08-01',
    arquivo: '/docs/it-004-2023.pdf',
    tags: ['classificação', 'risco', 'edificações'],
    palavrasChave: ['classificação', 'edificações', 'risco', 'incêndio'],
    popular: false,
    visualizacoes: 1120,
    downloads: 320,
    isActive: true,
    metadata: {},
    organizationId: 'cbm-pi',
    slug: 'classificacao-das-edificacoes',
    createdAt: '2023-02-01T00:00:00Z',
    updatedAt: '2023-08-01T00:00:00Z'
  }
];